---
- name: Show standby configs
  hosts: DSW1
  gather_facts: false
  tasks:
    - name: Waiting for HSRP ending its negotiation
      pause:
        seconds: 40
    - name: Run show standby
      cisco.ios.ios_command:
        commands:
          - command: show standby
      register: output
    - name: show standby
      debug:
        msg: '{{ output.stdout_lines[0] }}'
    - name: Time to check configs
      pause:
        seconds: 20
