---
- name: Show interfaces
  hosts: DSW1
  tasks:
    - name: Run show ip interface brief
      cisco.ios.ios_command:
        commands: [show ip interface brief]
      register: output
    - name: Display raw output
      debug:
        var: output.stdout_lines[0]
