---
ospf_processes:
  - process_id: 1
    router_id: 5.5.5.5
    reference_bandwidth: 1000000
ospf_interfaces:
  - name: Loopback0
    area: '0'
    process_id: '1'
  - name: Ethernet0/0
    bandwidth: '100'
    area: '0'
    process_id: '1'
  - name: Ethernet0/1
  - name: Ethernet0/2
    network_type: point-to-point
    ospf_authentication_key: Cisco
    area: '0'
    process_id: '1'
  - name: Ethernet0/3
