---
- name: Show vrrp configs
  hosts: DSW2
  gather_facts: false
  tasks:
    - name: Run show vrrp
      cisco.ios.ios_command:
        commands:
          - command: show vrrp
      register: output
    - name: show vrrp
      debug:
        msg: '{{ output.stdout_lines[0] }}'
    - name: If DSW1's eth0/1 uplink is shut down, DSW2 must immediately become the
        Active router for group 10.
      pause:
        seconds: 20
