---
- name: Track interface Ethernet0/1
  hosts: DSW1
  gather_facts: false
  tasks:
    - name: Track the interface
      cisco.ios.ios_config:
        lines: [track 10 interface Ethernet0/1 line-protocol]
