---
- name: Ping and traceroute External Server
  hosts: SRV1
  gather_facts: false
  vars:
    ansible_command_timeout: 300
  tasks:
    - name: Ping
      cisco.ios.ios_ping:
        dest: 10.32.1.100
      register: output
    - name: show ping output
      debug:
        var: output
    - name: Time to check a ping's output
      pause:
        seconds: 10
    - name: traceroute External Server
      cisco.ios.ios_command:
        commands: traceroute 10.32.1.100
      register: output0
    - name: show traceroute output
      debug:
        var: output0.stdout_lines[0]
    - name: Traceroute from SRV1 (10.10.1.100) to EXT1(10.32.1.100) must go via
        the path DSW1-R3-EXT1
      pause:
        seconds: 20
