---
- name: Assign the new interface in cisco devices
  hosts: OSPF-SINGLE-AREA
  gather_facts: false
  tasks:
    - name: Assign interfaces
      cisco.ios.ios_config:
        lines: "{{ lookup('template', 'interfaces.j2') }}"
